# Generated by Django 3.2 on 2021-04-29 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
